[build]
    #publish = "public"
    command = "hugo "
    environment = { HUGO_VERSION = "0.70.0" }

[context.production]
    HUGO_VERSION = "0.70.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    command = "grunt lunr-index && hugo" #always rebuild the search index for LIVE

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.staging] # 'staging' is a branch name
    command = "grunt lunr-index && hugo"
    [context.staging.environment]
    HUGO_ENV = "staging"
    HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/services/atlassian-partner"
  to = "/partners/atlassian"
  status = 301
  force = false


#####################################################
#                                                   #
# Trying to get beta plug-ins working - giving up   #
#                                                   #
#####################################################

#[[plugins]]
#package = "netlify-plugin-a11y"
#
#   # all inputs are optional, we just show you the defaults below
#    [plugins.inputs]
#
#   # required config
#   checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on
#
#   ## Another checkPaths Example
#   #checkPaths = [
#   #  '/blog',
#   #  '/about.html',
#   #  '/super/specific/route/index.html',
#   #]
#
#   # # optional config
#   resultMode = "warn" # is "error" by default
#
#   # # Developer only
#   # debugMode = true # extra logging for plugin developers

#[[plugins]]
#package = "netlify-plugin-no-more-404"
#
#  # all inputs are optional, we just show you the defaults below
#    [plugins.inputs]
#
#  # either "warn" or "error"
#    on404 = "warn"
#
#  # change this key to a new one any time you need to restart from scratch
#    cacheKey = "MyCacheKey"
#
#  # (for development) turn true for extra diagnostic logging
#    debugMode = false

#[[plugins]]
#package = "netlify-plugin-subfont"
#
#  [plugins.inputs]
#  # An array of glob patterns for pages on your site
#   # Recursive traversal will start from these
#  entryPoints = [
#    "*.html",
#  ]
#
#  # Follow your links across all pages to optimize the fonts across the antire site
#  recursive = true
#
#  # Subfont lets you set CSS font-display value of the optimized subsets
#  # See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
#  fontDisplay = "swap"
#
#  # Inline generated CSS @font-face blocks into each page
#  # When set to `false` an external CSS file will be created
#   inlineCss = false
#
#  # Inline generated font subsets into their respective @font-face blocks
#  # When set to `false` external font files will be created
#  inlineFonts = false
    
#[[plugins]]
#package = "netlify-plugin-checklinks"

# [plugins.inputs]
# # An array of glob patterns for pages on your site
# # Recursive traversal will start from these
# entryPoints = [
#   "*.html",
# ]

# # Recurse through all the links and asset references on your page, starting
# # at the entrypoints
# recursive = true

# # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
# # by default. Enabling pretty mode makes the output easier on the eyes.
# pretty = true

# # You can mark some check as skipped, which will block checklinks
# # from ever attempting to execute them.
# # skipPatterns is an array of strings you can match against failing reports
# skipPatterns = []

# # You can mark some check as todo, which will execute the check, but allow failures.
# # todoPatterns is an array of strings you can match against failing reports
# todoPatterns = []

# # Report on all broken links to external pages.
# # Enabling this will make your tests more brittle, since you can't control
# # external pages.
# checkExternal = false

# # Enable to check references to source maps, source map sources etc.
# # Many build tools don't emit working references, so this is disabled by default
# followSourceMaps = false